const KEY='mon-organiseur-drive-v33';
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const today=()=>new Date().toISOString().slice(0,10);
const starter=()=>({activePlan:0,plans:[{id:uid(),title:'Plan de travail',buckets:[
 {id:uid(),title:'À faire',tasks:[{id:uid(),title:'Préparer la liste des achats',notes:'Exemple de tâche modifiable.',assignee:'Christophe',dueDate:'',priority:'normal',progress:'todo',labels:['achat'],checklist:[{text:'Comparer les prix',done:false},{text:'Commander',done:false}]}]},
 {id:uid(),title:'En cours',tasks:[]},{id:uid(),title:'Terminé',tasks:[]}
]}]});
let db=load(), view='board', drag=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function load(){try{return JSON.parse(localStorage.getItem(KEY))||starter()}catch{return starter()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db)); scheduleDriveAutosave();}
function plan(){return db.plans[db.activePlan]||db.plans[0]}
function allTasks(){return plan().buckets.flatMap(b=>b.tasks.map(t=>({...t,bucket:b}))) }
function isLate(t){return t.dueDate && t.progress!=='done' && t.dueDate<today()}
function pass(t){const q=$('searchInput').value.toLowerCase();const f=$('filterStatus').value;const text=[t.title,t.notes,t.assignee,t.dueDate,t.priority,t.progress,...(t.labels||[])].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(f==='todo'&&t.progress==='done')return false;if(f==='done'&&t.progress!=='done')return false;if(f==='late'&&!isLate(t))return false;return true}
function render(){renderPlans();$('planTitle').value=plan().title;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(view+'View').classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); if(view==='board')renderBoard(); if(view==='list')renderList(); if(view==='calendar')renderCalendar(); if(view==='stats')renderStats(); save()}
function renderPlans(){ $('plansList').innerHTML=db.plans.map((p,i)=>`<div class="planItem ${i===db.activePlan?'active':''}" data-i="${i}">${esc(p.title)}</div>`).join(''); document.querySelectorAll('.planItem').forEach(el=>el.onclick=()=>{db.activePlan=+el.dataset.i;render()}) }
function renderBoard(){const root=$('boardView');root.innerHTML='';plan().buckets.forEach(b=>{const sec=document.createElement('section');sec.className='bucket';sec.innerHTML=`<div class="bucketHead"><input value="${esc(b.title)}"><span class="count">${b.tasks.length}</span></div><button class="addCard no-print">+ Ajouter une tâche</button><div class="cards"></div>`;sec.querySelector('input').onchange=e=>{b.title=e.target.value;render()};sec.querySelector('.addCard').onclick=()=>openTask(null,b.id);const cards=sec.querySelector('.cards');cards.ondragover=e=>{e.preventDefault();cards.classList.add('dragover')};cards.ondragleave=()=>cards.classList.remove('dragover');cards.ondrop=()=>{cards.classList.remove('dragover');if(drag){moveTask(drag,b.id);drag=null;render()}};b.tasks.filter(pass).forEach(t=>cards.appendChild(card(t,b.id)));root.appendChild(sec)})}
function card(t,bid){const el=document.createElement('article');el.className='card '+(t.progress==='done'?'done':'');el.draggable=true;el.ondragstart=()=>drag=t.id;el.onclick=()=>openTask(t.id,bid);const done=(t.checklist||[]).filter(x=>x.done).length,total=(t.checklist||[]).length;el.innerHTML=`<h3>${t.progress==='done'?'✅ ':''}${esc(t.title)}</h3><div class="meta">${t.priority!=='low'?`<span class="pill ${t.priority}">${prio(t.priority)}</span>`:''}${t.dueDate?`<span class="pill ${isLate(t)?'late':''}">📅 ${esc(t.dueDate)}</span>`:''}${t.assignee?`<span class="pill">👤 ${esc(t.assignee)}</span>`:''}</div>${(t.labels||[]).length?`<div class="meta">${t.labels.map(l=>`<span class="pill">${esc(l)}</span>`).join('')}</div>`:''}${total?`<div class="small">Checklist : ${done}/${total}</div>`:''}`;return el}
function renderList(){const rows=allTasks().filter(pass).map(t=>`<tr class="taskrow" data-id="${t.id}"><td>${t.progress==='done'?'✅':'⬜'} ${esc(t.title)}</td><td>${esc(t.bucket.title)}</td><td>${esc(t.assignee||'')}</td><td>${esc(t.dueDate||'')}</td><td>${prio(t.priority)}</td></tr>`).join('');$('listView').innerHTML=`<table class="listTable"><thead><tr><th>Tâche</th><th>Colonne</th><th>Responsable</th><th>Date</th><th>Priorité</th></tr></thead><tbody>${rows||'<tr><td>Aucune tâche trouvée.</td></tr>'}</tbody></table>`;document.querySelectorAll('.taskrow').forEach(r=>r.onclick=()=>openTask(r.dataset.id))}
function renderCalendar(){const dated=allTasks().filter(t=>t.dueDate&&pass(t)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('calendarView').innerHTML=`<div class="calendarGrid">${dated.map(t=>`<div class="day"><h3>${esc(t.dueDate)} ${isLate(t)?'⚠️':''}</h3><p><strong>${esc(t.title)}</strong></p><p>${esc(t.assignee||'')}</p></div>`).join('')||'<p>Aucune échéance.</p>'}</div>`}
function renderStats(){const tasks=allTasks();const done=tasks.filter(t=>t.progress==='done').length;const late=tasks.filter(isLate).length;$('statsView').innerHTML=`<div class="statsGrid"><div class="stat"><strong>${tasks.length}</strong><br>Tâches</div><div class="stat"><strong>${done}</strong><br>Terminées</div><div class="stat"><strong>${tasks.length-done}</strong><br>Restantes</div><div class="stat"><strong>${late}</strong><br>En retard</div></div>`}
function prio(p){return {low:'Basse',normal:'Normale',high:'Haute',urgent:'Urgente'}[p]||p}
function findTask(id){for(const b of plan().buckets){const t=b.tasks.find(x=>x.id===id);if(t)return {t,b}}return {}}
function moveTask(id,bid){const {t}=findTask(id);if(!t)return;plan().buckets.forEach(b=>b.tasks=b.tasks.filter(x=>x.id!==id));plan().buckets.find(b=>b.id===bid).tasks.push(t)}
function openTask(id,bid){const {t,b}=id?findTask(id):{};$('dialogTitle').textContent=id?'Modifier la tâche':'Nouvelle tâche';$('taskId').value=id||'';$('taskTitle').value=t?.title||'';$('taskNotes').value=t?.notes||'';$('taskAssignee').value=t?.assignee||'';$('taskDueDate').value=t?.dueDate||'';$('taskPriority').value=t?.priority||'normal';$('taskProgress').value=t?.progress||'todo';$('taskLabels').value=(t?.labels||[]).join(', ');$('taskChecklist').value=(t?.checklist||[]).map(x=>(x.done?'[x] ':'')+x.text).join('\n');$('taskBucket').innerHTML=plan().buckets.map(bb=>`<option value="${bb.id}">${esc(bb.title)}</option>`).join('');$('taskBucket').value=(b||plan().buckets.find(x=>x.id===bid)||plan().buckets[0]).id;$('deleteTaskBtn').style.visibility=id?'visible':'hidden';$('taskDialog').showModal()}
function checklistFrom(txt){return txt.split('\n').map(s=>s.trim()).filter(Boolean).map(s=>({done:/^\[x\]/i.test(s),text:s.replace(/^\[x\]\s*/i,'')}))}
$('taskForm').onsubmit=e=>{e.preventDefault();const id=$('taskId').value||uid();const old=findTask(id).t;const t={id,title:$('taskTitle').value.trim(),notes:$('taskNotes').value.trim(),assignee:$('taskAssignee').value.trim(),dueDate:$('taskDueDate').value,priority:$('taskPriority').value,progress:$('taskProgress').value,labels:$('taskLabels').value.split(',').map(x=>x.trim()).filter(Boolean),checklist:checklistFrom($('taskChecklist').value)};plan().buckets.forEach(b=>b.tasks=b.tasks.filter(x=>x.id!==id));const targetBucket=plan().buckets.find(b=>b.id===$('taskBucket').value); if(old){targetBucket.tasks.push(t)}else{targetBucket.tasks.unshift(t)}$('taskDialog').close();render()};
$('deleteTaskBtn').onclick=()=>{const id=$('taskId').value;if(confirm('Supprimer cette tâche ?')){plan().buckets.forEach(b=>b.tasks=b.tasks.filter(t=>t.id!==id));$('taskDialog').close();render()}};
$('cancelDialog').onclick=()=>$('taskDialog').close();$('planTitle').onchange=e=>{plan().title=e.target.value;render()};$('addBucketBtn').onclick=()=>{const title=prompt('Nom de la colonne ?','Nouvelle colonne');if(title){plan().buckets.push({id:uid(),title,tasks:[]});render()}};$('addTaskTopBtn').onclick=()=>openTask(null,plan().buckets[0].id);$('newPlanBtn').onclick=()=>{const title=prompt('Nom du nouveau plan ?','Nouveau plan');if(title){db.plans.push({id:uid(),title,buckets:[{id:uid(),title:'À faire',tasks:[]},{id:uid(),title:'En cours',tasks:[]},{id:uid(),title:'Terminé',tasks:[]}]});db.activePlan=db.plans.length-1;render()}};document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{view=n.dataset.view;render()});$('searchInput').oninput=render;$('filterStatus').onchange=render;$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='mon-organiseur-sauvegarde.json';a.click()};$('importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);render()}catch{alert('Fichier non valide')}};r.readAsText(f)};$('resetBtn').onclick=()=>{if(confirm('Tout effacer et remettre le modèle de départ ?')){db=starter();render()}};

function setPrintMode(mode){document.body.classList.remove('print-only-board','print-only-list','print-only-calendar','print-only-stats','print-only-all'); if(mode&&mode!=='current')document.body.classList.add('print-only-'+mode)}
function printChoice(choice){ if(!choice) return; if(choice==='current'){setPrintMode(view)}else{setPrintMode(choice)} setTimeout(()=>{window.print(); setTimeout(()=>setPrintMode(''),400)},80); $('printSelect').value=''; }
$('printSelect')?.addEventListener('change',e=>printChoice(e.target.value));

// ---------------- GOOGLE DRIVE SYNC ----------------
const DRIVE_SCOPE = 'https://www.googleapis.com/auth/drive.file';
const DRIVE_DISCOVERY = 'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest';
const DRIVE_FILENAME = 'mon-organiseur-drive-data.json';
const CLIENT_ID_KEY = 'mon-organiseur-google-client-id';
let tokenClient = null;
let driveReady = false;
let driveFileId = localStorage.getItem('mon-organiseur-drive-file-id') || '';
let autosaveTimer = null;
let lastSavedSnapshot = '';
function status(msg){ const el=$('syncStatus'); if(el) el.textContent = msg; }
function clientId(){ return localStorage.getItem(CLIENT_ID_KEY) || ''; }
function scheduleDriveAutosave(){ if(!driveReady) return; clearTimeout(autosaveTimer); autosaveTimer = setTimeout(()=>saveToDrive(true), 1200); }
function initDriveUi(){ const input=$('googleClientId'); if(input) input.value=clientId(); $('saveClientIdBtn')?.addEventListener('click',()=>{ const v=$('googleClientId').value.trim(); if(!v){alert('Colle ton Client ID Google.');return;} localStorage.setItem(CLIENT_ID_KEY,v); status('Client ID enregistré. Clique sur “Se connecter à Google Drive”.'); }); $('connectDriveBtn')?.addEventListener('click',connectDrive); $('loadDriveBtn')?.addEventListener('click',loadFromDrive); $('saveDriveBtn')?.addEventListener('click',()=>saveToDrive(false)); $('disconnectDriveBtn')?.addEventListener('click',disconnectDrive); }
async function connectDrive(){ const cid=clientId(); if(!cid){ alert('Il faut d’abord créer/coller le Client ID Google. Voir README.'); return; } status('Connexion Google en cours...'); await new Promise(resolve=>gapi.load('client',resolve)); await gapi.client.init({discoveryDocs:[DRIVE_DISCOVERY]}); tokenClient = google.accounts.oauth2.initTokenClient({ client_id: cid, scope: DRIVE_SCOPE, callback: async (resp)=>{ if(resp.error){ status('Connexion refusée.'); return; } driveReady=true; status('Drive connecté. Chargement de la sauvegarde...'); await loadFromDrive(true); scheduleDriveAutosave(); }}); tokenClient.requestAccessToken({prompt:'consent'}); }
function disconnectDrive(){ const token=gapi?.client?.getToken?.(); if(token) google.accounts.oauth2.revoke(token.access_token); gapi.client.setToken(''); driveReady=false; status('Drive déconnecté.'); }
async function findDriveFile(){ const res=await gapi.client.drive.files.list({ q:`name='${DRIVE_FILENAME}' and trashed=false`, spaces:'drive', fields:'files(id,name,modifiedTime)', pageSize:10 }); const file=(res.result.files||[])[0]; if(file){ driveFileId=file.id; localStorage.setItem('mon-organiseur-drive-file-id',driveFileId); return file.id; } return ''; }
async function loadFromDrive(silent=false){ if(!driveReady){ if(!silent) alert('Connecte d’abord Google Drive.'); return; } try{ let id=driveFileId || await findDriveFile(); if(!id){ status('Aucune sauvegarde Drive trouvée. Une nouvelle sera créée.'); await saveToDrive(true); return; } const res=await gapi.client.drive.files.get({fileId:id, alt:'media'}); const incoming=typeof res.body==='string'?JSON.parse(res.body):res.result; if(incoming && incoming.plans){ db=incoming; localStorage.setItem(KEY,JSON.stringify(db)); render(); status('Données chargées depuis Google Drive.'); } }catch(e){ console.error(e); if(!silent) alert('Impossible de charger depuis Drive.'); status('Erreur de chargement Drive.'); } }
async function saveToDrive(silent=false){ if(!driveReady) return; const snapshot=JSON.stringify(db,null,2); if(snapshot===lastSavedSnapshot && silent) return; try{ status('Sauvegarde Drive...'); let id=driveFileId || await findDriveFile(); const metadata={name:DRIVE_FILENAME,mimeType:'application/json'}; const boundary='-------monplanner'+Date.now(); const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+snapshot+'\r\n--'+boundary+'--'; const path=id?`/upload/drive/v3/files/${id}`:'/upload/drive/v3/files'; const method=id?'PATCH':'POST'; const res=await gapi.client.request({path,method,params:{uploadType:'multipart'},headers:{'Content-Type':'multipart/related; boundary='+boundary},body}); if(res.result.id){ driveFileId=res.result.id; localStorage.setItem('mon-organiseur-drive-file-id',driveFileId); } lastSavedSnapshot=snapshot; status('Sauvegardé automatiquement sur Google Drive à '+new Date().toLocaleTimeString()); }catch(e){ console.error(e); if(!silent) alert('Impossible de sauvegarder sur Drive.'); status('Erreur de sauvegarde Drive.'); } }

render();
initDriveUi();
